/*
 * ReferenceDataAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.mulesoft.mocksvc.models;

import java.util.*;

public class AddressesItemBuilder {
    //the instance to build
    private AddressesItem addressesItem;

    /**
     * Default constructor to initialize the instance
     */
    public AddressesItemBuilder() {
        addressesItem = new AddressesItem();
    }

    public AddressesItemBuilder addressLine1(String addressLine1) {
        addressesItem.setAddressLine1(addressLine1);
        return this;
    }

    public AddressesItemBuilder addressLine2(String addressLine2) {
        addressesItem.setAddressLine2(addressLine2);
        return this;
    }

    public AddressesItemBuilder suburb(String suburb) {
        addressesItem.setSuburb(suburb);
        return this;
    }

    public AddressesItemBuilder state(String state) {
        addressesItem.setState(state);
        return this;
    }

    public AddressesItemBuilder postcode(String postcode) {
        addressesItem.setPostcode(postcode);
        return this;
    }

    public AddressesItemBuilder country(String country) {
        addressesItem.setCountry(country);
        return this;
    }

    public AddressesItemBuilder countryCode(String countryCode) {
        addressesItem.setCountryCode(countryCode);
        return this;
    }

    public AddressesItemBuilder addressType(String addressType) {
        addressesItem.setAddressType(addressType);
        return this;
    }

    public AddressesItemBuilder addressStatus(String addressStatus) {
        addressesItem.setAddressStatus(addressStatus);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public AddressesItem build() {
        return addressesItem;
    }
}