/*
 * ReferenceDataAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.mulesoft.mocksvc.models;

import java.util.*;

public class CalEligibilityResponseBuilder 
        extends CalEligibilityResponseBaseTypeBuilder {
    //the instance to build
    private CalEligibilityResponse calEligibilityResponse;

    /**
     * Default constructor to initialize the instance
     */
    public CalEligibilityResponseBuilder() {
        calEligibilityResponse = new CalEligibilityResponse();
    }

    public CalEligibilityResponseBuilder eligible(Boolean eligible) {
        calEligibilityResponse.setEligible(eligible);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public CalEligibilityResponse build() {
        return calEligibilityResponse;
    }
}