/*
 * ReferenceDataAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.mulesoft.mocksvc.models;

import java.util.*;

public class CalEligibilityResponseBaseTypeBuilder {
    //the instance to build
    private CalEligibilityResponseBaseType calEligibilityResponseBaseType;

    /**
     * Default constructor to initialize the instance
     */
    public CalEligibilityResponseBaseTypeBuilder() {
        calEligibilityResponseBaseType = new CalEligibilityResponseBaseType();
    }

    public CalEligibilityResponseBaseTypeBuilder death(DeathBaseType death) {
        calEligibilityResponseBaseType.setDeath(death);
        return this;
    }

    public CalEligibilityResponseBaseTypeBuilder tpd(TpdBaseType tpd) {
        calEligibilityResponseBaseType.setTpd(tpd);
        return this;
    }

    public CalEligibilityResponseBaseTypeBuilder ip(IpBaseType ip) {
        calEligibilityResponseBaseType.setIp(ip);
        return this;
    }

    public CalEligibilityResponseBaseTypeBuilder levelOfCover(LevelOfCoverEnum levelOfCover) {
        calEligibilityResponseBaseType.setLevelOfCover(levelOfCover);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public CalEligibilityResponseBaseType build() {
        return calEligibilityResponseBaseType;
    }
}