/*
 * ReferenceDataAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.mulesoft.mocksvc.models;

import java.util.*;

public class CalEligibilityRequestBuilder {
    //the instance to build
    private CalEligibilityRequest calEligibilityRequest;

    /**
     * Default constructor to initialize the instance
     */
    public CalEligibilityRequestBuilder() {
        calEligibilityRequest = new CalEligibilityRequest();
    }

    public CalEligibilityRequestBuilder age(String age) {
        calEligibilityRequest.setAge(age);
        return this;
    }

    public CalEligibilityRequestBuilder individual(IndividualBaseType individual) {
        calEligibilityRequest.setIndividual(individual);
        return this;
    }

    public CalEligibilityRequestBuilder eligibility(EligibilityBaseType eligibility) {
        calEligibilityRequest.setEligibility(eligibility);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public CalEligibilityRequest build() {
        return calEligibilityRequest;
    }
}