/*
 * ReferenceDataAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.mulesoft.mocksvc.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class CalEligibilityResponse 
        extends CalEligibilityResponseBaseType {
    private static final long serialVersionUID = -5370433978616930585L;
    private Boolean eligible;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("eligible")
    public Boolean getEligible ( ) { 
        return this.eligible;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("eligible")
    public void setEligible (Boolean value) { 
        this.eligible = value;
    }
 
}
 