/*
 * ReferenceDataAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.mulesoft.mocksvc.models;

import java.util.*;

public class CodesetItemBuilder {
    //the instance to build
    private CodesetItem codesetItem;

    /**
     * Default constructor to initialize the instance
     */
    public CodesetItemBuilder() {
        codesetItem = new CodesetItem();
    }

    public CodesetItemBuilder systemValue(String systemValue) {
        codesetItem.setSystemValue(systemValue);
        return this;
    }

    public CodesetItemBuilder cbusValue(String cbusValue) {
        codesetItem.setCbusValue(cbusValue);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public CodesetItem build() {
        return codesetItem;
    }
}