/*
 * ReferenceDataAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.mulesoft.mocksvc.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class CodesetItem 
        implements java.io.Serializable {
    private static final long serialVersionUID = -8687286906901832067L;
    private String systemValue;
    private String cbusValue;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("systemValue")
    public String getSystemValue ( ) { 
        return this.systemValue;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("systemValue")
    public void setSystemValue (String value) { 
        this.systemValue = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("cbusValue")
    public String getCbusValue ( ) { 
        return this.cbusValue;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("cbusValue")
    public void setCbusValue (String value) { 
        this.cbusValue = value;
    }
 
}
 