/*
 * ReferenceDataAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.mulesoft.mocksvc.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class Codeset 
        implements java.io.Serializable {
    private static final long serialVersionUID = 3070930358597189695L;
    private String codesetName;
    private List<CodesetItem> codeset;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("codesetName")
    public String getCodesetName ( ) { 
        return this.codesetName;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("codesetName")
    public void setCodesetName (String value) { 
        this.codesetName = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("codeset")
    public List<CodesetItem> getCodeset ( ) { 
        return this.codeset;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("codeset")
    public void setCodeset (List<CodesetItem> value) { 
        this.codeset = value;
    }
 
}
 