/*
 * ReferenceDataAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.mulesoft.mocksvc.models;

import java.util.*;

public class CodesetBuilder {
    //the instance to build
    private Codeset codesetInstance;

    /**
     * Default constructor to initialize the instance
     */
    public CodesetBuilder() {
        codesetInstance = new Codeset();
    }

    public CodesetBuilder codesetName(String codesetName) {
        codesetInstance.setCodesetName(codesetName);
        return this;
    }

    public CodesetBuilder codeset(List<CodesetItem> codeset) {
        codesetInstance.setCodeset(codeset);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Codeset build() {
        return codesetInstance;
    }
}