/*
 * ReferenceDataAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.mulesoft.mocksvc.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class CoverAmountsItem 
        implements java.io.Serializable {
    private static final long serialVersionUID = -208346435293153282L;
    private Double unit;
    private Double amount;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("unit")
    public Double getUnit ( ) { 
        return this.unit;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("unit")
    public void setUnit (Double value) { 
        this.unit = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("amount")
    public Double getAmount ( ) { 
        return this.amount;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("amount")
    public void setAmount (Double value) { 
        this.amount = value;
    }
 
}
 