/*
 * ReferenceDataAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.mulesoft.mocksvc.models;

import java.util.*;

public class CoverAmountsItemBuilder {
    //the instance to build
    private CoverAmountsItem coverAmountsItem;

    /**
     * Default constructor to initialize the instance
     */
    public CoverAmountsItemBuilder() {
        coverAmountsItem = new CoverAmountsItem();
    }

    public CoverAmountsItemBuilder unit(Double unit) {
        coverAmountsItem.setUnit(unit);
        return this;
    }

    public CoverAmountsItemBuilder amount(Double amount) {
        coverAmountsItem.setAmount(amount);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public CoverAmountsItem build() {
        return coverAmountsItem;
    }
}