/*
 * ReferenceDataAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.mulesoft.mocksvc.models;

import java.util.*;

public class DeathBaseTypeBuilder {
    //the instance to build
    private DeathBaseType deathBaseType;

    /**
     * Default constructor to initialize the instance
     */
    public DeathBaseTypeBuilder() {
        deathBaseType = new DeathBaseType();
    }

    public DeathBaseTypeBuilder cover(Double cover) {
        deathBaseType.setCover(cover);
        return this;
    }

    public DeathBaseTypeBuilder units(Double units) {
        deathBaseType.setUnits(units);
        return this;
    }

    public DeathBaseTypeBuilder costPerWeek(Double costPerWeek) {
        deathBaseType.setCostPerWeek(costPerWeek);
        return this;
    }

    public DeathBaseTypeBuilder maxUnits(Double maxUnits) {
        deathBaseType.setMaxUnits(maxUnits);
        return this;
    }

    public DeathBaseTypeBuilder defaultUnits(Double defaultUnits) {
        deathBaseType.setDefaultUnits(defaultUnits);
        return this;
    }

    public DeathBaseTypeBuilder coverAmounts(List<CoverAmountsItem> coverAmounts) {
        deathBaseType.setCoverAmounts(coverAmounts);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public DeathBaseType build() {
        return deathBaseType;
    }
}