/*
 * ReferenceDataAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.mulesoft.mocksvc.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class DefaultInsurance 
        implements java.io.Serializable {
    private static final long serialVersionUID = 6405619559646588024L;
    private DeathBaseType death;
    private TpdBaseType tpd;
    private IpBaseType ip;
    private LevelOfCoverEnum levelOfCover = LevelOfCoverEnum.AUTOMATIC;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("death")
    public DeathBaseType getDeath ( ) { 
        return this.death;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("death")
    public void setDeath (DeathBaseType value) { 
        this.death = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("tpd")
    public TpdBaseType getTpd ( ) { 
        return this.tpd;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("tpd")
    public void setTpd (TpdBaseType value) { 
        this.tpd = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("ip")
    public IpBaseType getIp ( ) { 
        return this.ip;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("ip")
    public void setIp (IpBaseType value) { 
        this.ip = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("levelOfCover")
    public LevelOfCoverEnum getLevelOfCover ( ) { 
        return this.levelOfCover;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("levelOfCover")
    public void setLevelOfCover (LevelOfCoverEnum value) { 
        this.levelOfCover = value;
    }
 
}
 