/*
 * ReferenceDataAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.mulesoft.mocksvc.models;

import java.util.*;

public class DefaultInsuranceBuilder {
    //the instance to build
    private DefaultInsurance defaultInsurance;

    /**
     * Default constructor to initialize the instance
     */
    public DefaultInsuranceBuilder() {
        defaultInsurance = new DefaultInsurance();
    }

    public DefaultInsuranceBuilder death(DeathBaseType death) {
        defaultInsurance.setDeath(death);
        return this;
    }

    public DefaultInsuranceBuilder tpd(TpdBaseType tpd) {
        defaultInsurance.setTpd(tpd);
        return this;
    }

    public DefaultInsuranceBuilder ip(IpBaseType ip) {
        defaultInsurance.setIp(ip);
        return this;
    }

    public DefaultInsuranceBuilder levelOfCover(LevelOfCoverEnum levelOfCover) {
        defaultInsurance.setLevelOfCover(levelOfCover);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public DefaultInsurance build() {
        return defaultInsurance;
    }
}