/*
 * ReferenceDataAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.mulesoft.mocksvc.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class EligibilityBaseType 
        implements java.io.Serializable {
    private static final long serialVersionUID = -1340563843346498770L;
    private Boolean paidTerminalBenefits;
    private Boolean illnessDeathWithin24Months;
    private Boolean offWorkDueToSickOrInjured;
    private Boolean employmentLastSixMonths;
    private Boolean workMinimum30Hours;
    private Boolean illnessOrAwayFromWork;
    private Boolean beenDeclinedOrHadExclusion;
    /** GETTER
     * Has a super fund or insurer ever processed or paid a TPD or Terminal illness benefit?
     */
    @JsonGetter("paidTerminalBenefits")
    public Boolean getPaidTerminalBenefits ( ) { 
        return this.paidTerminalBenefits;
    }
    
    /** SETTER
     * Has a super fund or insurer ever processed or paid a TPD or Terminal illness benefit?
     */
    @JsonSetter("paidTerminalBenefits")
    public void setPaidTerminalBenefits (Boolean value) { 
        this.paidTerminalBenefits = value;
    }
 
    /** GETTER
     * Have you been diagnosed with an illness that is likely to lead to your death within 24 months of the Date of Diagnosis?
     */
    @JsonGetter("illnessDeathWithin24Months")
    public Boolean getIllnessDeathWithin24Months ( ) { 
        return this.illnessDeathWithin24Months;
    }
    
    /** SETTER
     * Have you been diagnosed with an illness that is likely to lead to your death within 24 months of the Date of Diagnosis?
     */
    @JsonSetter("illnessDeathWithin24Months")
    public void setIllnessDeathWithin24Months (Boolean value) { 
        this.illnessDeathWithin24Months = value;
    }
 
    /** GETTER
     * Are you off work or on restricted duties because you are sick or injured?
     */
    @JsonGetter("offWorkDueToSickOrInjured")
    public Boolean getOffWorkDueToSickOrInjured ( ) { 
        return this.offWorkDueToSickOrInjured;
    }
    
    /** SETTER
     * Are you off work or on restricted duties because you are sick or injured?
     */
    @JsonSetter("offWorkDueToSickOrInjured")
    public void setOffWorkDueToSickOrInjured (Boolean value) { 
        this.offWorkDueToSickOrInjured = value;
    }
 
    /** GETTER
     * Have you started working with your current employer in the last six months?
     */
    @JsonGetter("employmentLastSixMonths")
    public Boolean getEmploymentLastSixMonths ( ) { 
        return this.employmentLastSixMonths;
    }
    
    /** SETTER
     * Have you started working with your current employer in the last six months?
     */
    @JsonSetter("employmentLastSixMonths")
    public void setEmploymentLastSixMonths (Boolean value) { 
        this.employmentLastSixMonths = value;
    }
 
    /** GETTER
     * Regardless of whether you are a full-time, part-time, or casual worker, are you able to do your normal job for a min. 30 hrs a week?
     */
    @JsonGetter("workMinimum30Hours")
    public Boolean getWorkMinimum30Hours ( ) { 
        return this.workMinimum30Hours;
    }
    
    /** SETTER
     * Regardless of whether you are a full-time, part-time, or casual worker, are you able to do your normal job for a min. 30 hrs a week?
     */
    @JsonSetter("workMinimum30Hours")
    public void setWorkMinimum30Hours (Boolean value) { 
        this.workMinimum30Hours = value;
    }
 
    /** GETTER
     * Have you been hospitalised for more than 5 days in a row over the last 12 months?
     */
    @JsonGetter("illnessOrAwayFromWork")
    public Boolean getIllnessOrAwayFromWork ( ) { 
        return this.illnessOrAwayFromWork;
    }
    
    /** SETTER
     * Have you been hospitalised for more than 5 days in a row over the last 12 months?
     */
    @JsonSetter("illnessOrAwayFromWork")
    public void setIllnessOrAwayFromWork (Boolean value) { 
        this.illnessOrAwayFromWork = value;
    }
 
    /** GETTER
     * Have either of the following happened to you - Have you ever been declined income protection, death, TPD cover by any insurance company?
     */
    @JsonGetter("beenDeclinedOrHadExclusion")
    public Boolean getBeenDeclinedOrHadExclusion ( ) { 
        return this.beenDeclinedOrHadExclusion;
    }
    
    /** SETTER
     * Have either of the following happened to you - Have you ever been declined income protection, death, TPD cover by any insurance company?
     */
    @JsonSetter("beenDeclinedOrHadExclusion")
    public void setBeenDeclinedOrHadExclusion (Boolean value) { 
        this.beenDeclinedOrHadExclusion = value;
    }
 
}
 