/*
 * ReferenceDataAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.mulesoft.mocksvc.models;

import java.util.*;

public class EligibilityBaseTypeBuilder {
    //the instance to build
    private EligibilityBaseType eligibilityBaseType;

    /**
     * Default constructor to initialize the instance
     */
    public EligibilityBaseTypeBuilder() {
        eligibilityBaseType = new EligibilityBaseType();
    }

    /**
     * Has a super fund or insurer ever processed or paid a TPD or Terminal illness benefit?
     */
    public EligibilityBaseTypeBuilder paidTerminalBenefits(Boolean paidTerminalBenefits) {
        eligibilityBaseType.setPaidTerminalBenefits(paidTerminalBenefits);
        return this;
    }

    /**
     * Have you been diagnosed with an illness that is likely to lead to your death within 24 months of the Date of Diagnosis?
     */
    public EligibilityBaseTypeBuilder illnessDeathWithin24Months(Boolean illnessDeathWithin24Months) {
        eligibilityBaseType.setIllnessDeathWithin24Months(illnessDeathWithin24Months);
        return this;
    }

    /**
     * Are you off work or on restricted duties because you are sick or injured?
     */
    public EligibilityBaseTypeBuilder offWorkDueToSickOrInjured(Boolean offWorkDueToSickOrInjured) {
        eligibilityBaseType.setOffWorkDueToSickOrInjured(offWorkDueToSickOrInjured);
        return this;
    }

    /**
     * Have you started working with your current employer in the last six months?
     */
    public EligibilityBaseTypeBuilder employmentLastSixMonths(Boolean employmentLastSixMonths) {
        eligibilityBaseType.setEmploymentLastSixMonths(employmentLastSixMonths);
        return this;
    }

    /**
     * Regardless of whether you are a full-time, part-time, or casual worker, are you able to do your normal job for a min. 30 hrs a week?
     */
    public EligibilityBaseTypeBuilder workMinimum30Hours(Boolean workMinimum30Hours) {
        eligibilityBaseType.setWorkMinimum30Hours(workMinimum30Hours);
        return this;
    }

    /**
     * Have you been hospitalised for more than 5 days in a row over the last 12 months?
     */
    public EligibilityBaseTypeBuilder illnessOrAwayFromWork(Boolean illnessOrAwayFromWork) {
        eligibilityBaseType.setIllnessOrAwayFromWork(illnessOrAwayFromWork);
        return this;
    }

    /**
     * Have either of the following happened to you - Have you ever been declined income protection, death, TPD cover by any insurance company?
     */
    public EligibilityBaseTypeBuilder beenDeclinedOrHadExclusion(Boolean beenDeclinedOrHadExclusion) {
        eligibilityBaseType.setBeenDeclinedOrHadExclusion(beenDeclinedOrHadExclusion);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public EligibilityBaseType build() {
        return eligibilityBaseType;
    }
}