/*
 * ReferenceDataAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.mulesoft.mocksvc.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class GivenNamesItem 
        implements java.io.Serializable {
    private static final long serialVersionUID = -2183164843165621249L;
    private String name;
    private int sequence;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("name")
    public String getName ( ) { 
        return this.name;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("name")
    public void setName (String value) { 
        this.name = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("sequence")
    public int getSequence ( ) { 
        return this.sequence;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("sequence")
    public void setSequence (int value) { 
        this.sequence = value;
    }
 
}
 