/*
 * ReferenceDataAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.mulesoft.mocksvc.models;

import java.util.*;

public class GivenNamesItemBuilder {
    //the instance to build
    private GivenNamesItem givenNamesItem;

    /**
     * Default constructor to initialize the instance
     */
    public GivenNamesItemBuilder() {
        givenNamesItem = new GivenNamesItem();
    }

    public GivenNamesItemBuilder name(String name) {
        givenNamesItem.setName(name);
        return this;
    }

    public GivenNamesItemBuilder sequence(int sequence) {
        givenNamesItem.setSequence(sequence);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public GivenNamesItem build() {
        return givenNamesItem;
    }
}