/*
 * ReferenceDataAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.mulesoft.mocksvc.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.mulesoft.mocksvc.DateTimeHelper;
import org.joda.time.LocalDate;

public class IndividualBaseType 
        implements java.io.Serializable {
    private static final long serialVersionUID = -96813247434728603L;
    private String id;
    private String title;
    private List<GivenNamesItem> givenNames;
    private String lastName;
    private String gender;
    private LocalDate dateOfBirth;
    private List<AddressesItem> addresses;
    private String contactPreference;
    private String emailAddress;
    private String businessPhoneNumber;
    private String afterHoursPhoneNumber;
    private String mobilePhoneNumber;
    private String taxFileNumber;
    private Boolean tFNSupplied;
    private String occupationalCategory;
    private String occupation;
    private String employmentStatus;
    private String membershipDivision;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("id")
    public String getId ( ) { 
        return this.id;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("id")
    public void setId (String value) { 
        this.id = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("title")
    public String getTitle ( ) { 
        return this.title;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("title")
    public void setTitle (String value) { 
        this.title = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("givenNames")
    public List<GivenNamesItem> getGivenNames ( ) { 
        return this.givenNames;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("givenNames")
    public void setGivenNames (List<GivenNamesItem> value) { 
        this.givenNames = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("lastName")
    public String getLastName ( ) { 
        return this.lastName;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("lastName")
    public void setLastName (String value) { 
        this.lastName = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("gender")
    public String getGender ( ) { 
        return this.gender;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("gender")
    public void setGender (String value) { 
        this.gender = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("dateOfBirth")
    @JsonSerialize(using=DateTimeHelper.SimpleDateSerializer.class)
    public LocalDate getDateOfBirth ( ) { 
        return this.dateOfBirth;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("dateOfBirth")
    @JsonDeserialize(using=DateTimeHelper.SimpleDateDeserializer.class)
    public void setDateOfBirth (LocalDate value) { 
        this.dateOfBirth = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("addresses")
    public List<AddressesItem> getAddresses ( ) { 
        return this.addresses;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("addresses")
    public void setAddresses (List<AddressesItem> value) { 
        this.addresses = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("contactPreference")
    public String getContactPreference ( ) { 
        return this.contactPreference;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("contactPreference")
    public void setContactPreference (String value) { 
        this.contactPreference = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("emailAddress")
    public String getEmailAddress ( ) { 
        return this.emailAddress;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("emailAddress")
    public void setEmailAddress (String value) { 
        this.emailAddress = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("businessPhoneNumber")
    public String getBusinessPhoneNumber ( ) { 
        return this.businessPhoneNumber;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("businessPhoneNumber")
    public void setBusinessPhoneNumber (String value) { 
        this.businessPhoneNumber = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("afterHoursPhoneNumber")
    public String getAfterHoursPhoneNumber ( ) { 
        return this.afterHoursPhoneNumber;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("afterHoursPhoneNumber")
    public void setAfterHoursPhoneNumber (String value) { 
        this.afterHoursPhoneNumber = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("mobilePhoneNumber")
    public String getMobilePhoneNumber ( ) { 
        return this.mobilePhoneNumber;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("mobilePhoneNumber")
    public void setMobilePhoneNumber (String value) { 
        this.mobilePhoneNumber = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("taxFileNumber")
    public String getTaxFileNumber ( ) { 
        return this.taxFileNumber;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("taxFileNumber")
    public void setTaxFileNumber (String value) { 
        this.taxFileNumber = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("tFNSupplied")
    public Boolean getTFNSupplied ( ) { 
        return this.tFNSupplied;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("tFNSupplied")
    public void setTFNSupplied (Boolean value) { 
        this.tFNSupplied = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("occupationalCategory")
    public String getOccupationalCategory ( ) { 
        return this.occupationalCategory;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("occupationalCategory")
    public void setOccupationalCategory (String value) { 
        this.occupationalCategory = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("occupation")
    public String getOccupation ( ) { 
        return this.occupation;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("occupation")
    public void setOccupation (String value) { 
        this.occupation = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("employmentStatus")
    public String getEmploymentStatus ( ) { 
        return this.employmentStatus;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("employmentStatus")
    public void setEmploymentStatus (String value) { 
        this.employmentStatus = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("membershipDivision")
    public String getMembershipDivision ( ) { 
        return this.membershipDivision;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("membershipDivision")
    public void setMembershipDivision (String value) { 
        this.membershipDivision = value;
    }
 
}
 