/*
 * ReferenceDataAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.mulesoft.mocksvc.models;

import java.util.*;

public class IpBaseTypeBuilder {
    //the instance to build
    private IpBaseType ipBaseType;

    /**
     * Default constructor to initialize the instance
     */
    public IpBaseTypeBuilder() {
        ipBaseType = new IpBaseType();
    }

    public IpBaseTypeBuilder cover(Double cover) {
        ipBaseType.setCover(cover);
        return this;
    }

    public IpBaseTypeBuilder units(Double units) {
        ipBaseType.setUnits(units);
        return this;
    }

    public IpBaseTypeBuilder costPerWeek(Double costPerWeek) {
        ipBaseType.setCostPerWeek(costPerWeek);
        return this;
    }

    public IpBaseTypeBuilder maxUnits(Double maxUnits) {
        ipBaseType.setMaxUnits(maxUnits);
        return this;
    }

    public IpBaseTypeBuilder defaultUnits(Double defaultUnits) {
        ipBaseType.setDefaultUnits(defaultUnits);
        return this;
    }

    public IpBaseTypeBuilder coverAmounts(List<CoverAmountsItem> coverAmounts) {
        ipBaseType.setCoverAmounts(coverAmounts);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public IpBaseType build() {
        return ipBaseType;
    }
}