/*
 * ReferenceDataAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.mulesoft.mocksvc.models;

import java.util.ArrayList;
import java.util.List;
import java.util.TreeMap;

public enum LevelOfCoverEnum {
    AUTOMATIC, //TODO: Write general description for this element
    EXTRA, //TODO: Write general description for this element
    REDUCED; //TODO: Write general description for this element

    private static TreeMap<String, LevelOfCoverEnum> valueMap = new TreeMap<String, LevelOfCoverEnum>();
    private String value;

    static {
        AUTOMATIC.value = "automatic";
        EXTRA.value = "extra";
        REDUCED.value = "reduced";

        valueMap.put("automatic", AUTOMATIC);
        valueMap.put("extra", EXTRA);
        valueMap.put("reduced", REDUCED);
    }

    /**
     * Returns the enum member associated with the given string value
     * @return The enum member against the given string value */
    @com.fasterxml.jackson.annotation.JsonCreator
    public static LevelOfCoverEnum fromString(String toConvert) {
        return valueMap.get(toConvert);
    }

    /**
     * Returns the string value associated with the enum member
     * @return The string value against enum member */
    @com.fasterxml.jackson.annotation.JsonValue
    public String value() {
        return value;
    }
        
    /**
     * Get string representation of this enum
     */
    @Override
    public String toString() {
        return value.toString();
    }

    /**
     * Convert list of LevelOfCoverEnum values to list of string values
     * @param toConvert The list of LevelOfCoverEnum values to convert
     * @return List of representative string values */
    public static List<String> toValue(List<LevelOfCoverEnum> toConvert) {
        if(toConvert == null)
            return null;
        List<String> convertedValues = new ArrayList<String>();
        for (LevelOfCoverEnum enumValue : toConvert) {
            convertedValues.add(enumValue.value);
        }
        return convertedValues;
    }
} 