/*
 * ReferenceDataAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.mulesoft.mocksvc.models;

import java.util.*;

public class ReferenceDataSuperFundsResponseBuilder {
    //the instance to build
    private ReferenceDataSuperFundsResponse referenceDataSuperFundsResponse;

    /**
     * Default constructor to initialize the instance
     */
    public ReferenceDataSuperFundsResponseBuilder() {
        referenceDataSuperFundsResponse = new ReferenceDataSuperFundsResponse();
    }

    public ReferenceDataSuperFundsResponseBuilder totalRecords(int totalRecords) {
        referenceDataSuperFundsResponse.setTotalRecords(totalRecords);
        return this;
    }

    public ReferenceDataSuperFundsResponseBuilder records(List<Object> records) {
        referenceDataSuperFundsResponse.setRecords(records);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public ReferenceDataSuperFundsResponse build() {
        return referenceDataSuperFundsResponse;
    }
}