/*
 * ReferenceDataAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.mulesoft.mocksvc.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class ReferenceDataSuperFundsResponse 
        implements java.io.Serializable {
    private static final long serialVersionUID = -9199243208686085713L;
    private int totalRecords;
    private List<Object> records;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("totalRecords")
    public int getTotalRecords ( ) { 
        return this.totalRecords;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("totalRecords")
    public void setTotalRecords (int value) { 
        this.totalRecords = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("records")
    public List<Object> getRecords ( ) { 
        return this.records;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("records")
    public void setRecords (List<Object> value) { 
        this.records = value;
    }
 
}
 