/*
 * ReferenceDataAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.mulesoft.mocksvc.models;

import java.util.*;

public class ReferenceDataSuperFundsResponse84Builder {
    //the instance to build
    private ReferenceDataSuperFundsResponse84 referenceDataSuperFundsResponse84;

    /**
     * Default constructor to initialize the instance
     */
    public ReferenceDataSuperFundsResponse84Builder() {
        referenceDataSuperFundsResponse84 = new ReferenceDataSuperFundsResponse84();
    }

    /**
     * The total number of records, retrieved by the search criteria
     */
    public ReferenceDataSuperFundsResponse84Builder totalRecords(int totalRecords) {
        referenceDataSuperFundsResponse84.setTotalRecords(totalRecords);
        return this;
    }

    /**
     * The found records. It can be empty if no records found.
     */
    public ReferenceDataSuperFundsResponse84Builder records(List<Object> records) {
        referenceDataSuperFundsResponse84.setRecords(records);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public ReferenceDataSuperFundsResponse84 build() {
        return referenceDataSuperFundsResponse84;
    }
}