/*
 * ReferenceDataAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.mulesoft.mocksvc.models;

import java.util.*;

public class ReferenceDataCodesetsResponse54Builder {
    //the instance to build
    private ReferenceDataCodesetsResponse54 referenceDataCodesetsResponse54;

    /**
     * Default constructor to initialize the instance
     */
    public ReferenceDataCodesetsResponse54Builder() {
        referenceDataCodesetsResponse54 = new ReferenceDataCodesetsResponse54();
    }

    /**
     * The total number of records, retrieved by the search criteria
     */
    public ReferenceDataCodesetsResponse54Builder totalRecords(int totalRecords) {
        referenceDataCodesetsResponse54.setTotalRecords(totalRecords);
        return this;
    }

    /**
     * The found records. It can be empty if no records found.
     */
    public ReferenceDataCodesetsResponse54Builder records(List<Object> records) {
        referenceDataCodesetsResponse54.setRecords(records);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public ReferenceDataCodesetsResponse54 build() {
        return referenceDataCodesetsResponse54;
    }
}