/*
 * ReferenceDataAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.mulesoft.mocksvc.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class TpdBaseType 
        implements java.io.Serializable {
    private static final long serialVersionUID = 210118117044127213L;
    private Double cover;
    private Double units;
    private Double costPerWeek;
    private Double maxUnits;
    private Double defaultUnits;
    private List<CoverAmountsItem> coverAmounts;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("cover")
    public Double getCover ( ) { 
        return this.cover;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("cover")
    public void setCover (Double value) { 
        this.cover = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("units")
    public Double getUnits ( ) { 
        return this.units;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("units")
    public void setUnits (Double value) { 
        this.units = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("costPerWeek")
    public Double getCostPerWeek ( ) { 
        return this.costPerWeek;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("costPerWeek")
    public void setCostPerWeek (Double value) { 
        this.costPerWeek = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("maxUnits")
    public Double getMaxUnits ( ) { 
        return this.maxUnits;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("maxUnits")
    public void setMaxUnits (Double value) { 
        this.maxUnits = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("defaultUnits")
    public Double getDefaultUnits ( ) { 
        return this.defaultUnits;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("defaultUnits")
    public void setDefaultUnits (Double value) { 
        this.defaultUnits = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("coverAmounts")
    public List<CoverAmountsItem> getCoverAmounts ( ) { 
        return this.coverAmounts;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("coverAmounts")
    public void setCoverAmounts (List<CoverAmountsItem> value) { 
        this.coverAmounts = value;
    }
 
}
 