/*
 * ReferenceDataAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.mulesoft.mocksvc.models;

import java.util.*;

public class TpdBaseTypeBuilder {
    //the instance to build
    private TpdBaseType tpdBaseType;

    /**
     * Default constructor to initialize the instance
     */
    public TpdBaseTypeBuilder() {
        tpdBaseType = new TpdBaseType();
    }

    public TpdBaseTypeBuilder cover(Double cover) {
        tpdBaseType.setCover(cover);
        return this;
    }

    public TpdBaseTypeBuilder units(Double units) {
        tpdBaseType.setUnits(units);
        return this;
    }

    public TpdBaseTypeBuilder costPerWeek(Double costPerWeek) {
        tpdBaseType.setCostPerWeek(costPerWeek);
        return this;
    }

    public TpdBaseTypeBuilder maxUnits(Double maxUnits) {
        tpdBaseType.setMaxUnits(maxUnits);
        return this;
    }

    public TpdBaseTypeBuilder defaultUnits(Double defaultUnits) {
        tpdBaseType.setDefaultUnits(defaultUnits);
        return this;
    }

    public TpdBaseTypeBuilder coverAmounts(List<CoverAmountsItem> coverAmounts) {
        tpdBaseType.setCoverAmounts(coverAmounts);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public TpdBaseType build() {
        return tpdBaseType;
    }
}