/*
 * ReferenceDataAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.mulesoft.mocksvc;

import com.mulesoft.mocksvc.controllers.*;
import com.mulesoft.mocksvc.http.client.HttpClient;

public class ReferenceDataAPIClient {
    /**
     * Singleton access to Reference controller
     * @return	Returns the ReferenceController instance 
     */
    public ReferenceController getReference() {
        return ReferenceController.getInstance();
    }

    /**
     * Get the shared http client currently being used for API calls
     * @return The http client instance currently being used
     */
    public HttpClient getSharedHttpClient() {
        return BaseController.getClientInstance();
    }
    
    /**
     * Set a shared http client to be used for API calls
     * @param httpClient The http client to use
     */
    public void setSharedHttpClient(HttpClient httpClient) {
        BaseController.setClientInstance(httpClient);
    }

    /**
     * Default constructor 
     */     
    public ReferenceDataAPIClient() {
    }

}